### ISSUE TITLE
rethink the configuration of the log level

### ISSUE THREAD

**Issue by krabradosty** [xshellinc/isaax-reactor#3]
https://github.com/xshellinc/isaax-reactor/blob/master/lib/logger.js#L12

**Comment by yentsun** [comment]
The common practice is to control log level via environment, not config (as it requires commits). We just need everything documented and you just need to ask devops team to change the level - it won't happen too often.

Also, since there is no config module integrated (yet) to reactor, controlling level with config is not even possible

**Comment by dbsparkle** [comment]
Is this on hold?

**Comment by krabradosty** [comment]
@dbsparkle Yes, we can close it
